#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StrangeChat.Resource", IsApplication=true)]

namespace StrangeChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int start = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int uesr = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int LayLogPagBot = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int LayLogPagTop = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int LayResBot = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int LayResTop = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int Msg = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MsgAll = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int btnBack = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int btnEn = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int btnLBack = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int btnLMenu = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int btnLoMenu = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int btnLogin = 2131034121;
			
			// aapt resource value: 0x7f050016
			public const int btnMainMenu = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int btnMenu = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int btnRegister = 2131034122;
			
			// aapt resource value: 0x7f05001a
			public const int btnResBack = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int btnResEn = 2131034148;
			
			// aapt resource value: 0x7f05001c
			public const int btnResMenu = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int btnStart = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int editPwd = 2131034131;
			
			// aapt resource value: 0x7f050021
			public const int editResPwd = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int editResPwdAgn = 2131034147;
			
			// aapt resource value: 0x7f05001f
			public const int editResUser = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int editUser = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int layLoBottom = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int layLoTop = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int layMainBotton = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int layMainTop = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int send = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int textPwd = 2131034130;
			
			// aapt resource value: 0x7f050020
			public const int textResPwd = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int textResPwdAgn = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int textResUser = 2131034142;
			
			// aapt resource value: 0x7f050010
			public const int textUser = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int titleL = 2131034125;
			
			// aapt resource value: 0x7f05001b
			public const int titleRes = 2131034139;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Register = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
